dist: trusty
language: go
go_import_path: github.com/readhelper/vendor
sudo: false

go:
  - 1.6.4

env:
  global:
   - GO15VENDOREXPERIMENT=1
  matrix:
   - TARGET=amd64

matrix:
  fast_finish: true
  allow_failures:
    - go: tip
  exclude:
  - go: 1.6
    env: TARGET=arm64

before_install:
 #- go get -v github.com/chzchzchz/goword
 #- go get -v honnef.co/go/simple/cmd/gosimple
 #- go get -v honnef.co/go/unused/cmd/unused

# disable godep restore override
install:
# - pushd cmd/ && go get -t -v ./... && popd

script:
 - >
      GOARCH="${TARGET}" ./build;