dist: trusty
language: go
go_import_path: github.com/readhelper/beedemo
sudo: false

go:
  - 1.7.4

env:
  global:
   - GO15VENDOREXPERIMENT=1
  matrix:
   - TARGET=amd64

matrix:
  fast_finish: true
  allow_failures:
    - go: tip
  exclude:
  - go: 1.6
    env: TARGET=arm64

before_install:
 #- go get -v github.com/coreos/etcd
 #- go get -v github.com/astaxie/beego
 #- go get -v honnef.co/go/unused/cmd/unused

# disable godep restore override
install:
 - go get -t -v ./hellogo/...

script:
 - go test ./hellogo/... -cover
 - cd ./hellogo; go build